apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: cluster-config
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: quackersbank
  path: ./infrastructure
  prune: true